### ISSUE TITLE
I can't find a match for Device #'s in BOM

### ISSUE THREAD

**Issue by ikanode** [jaymzx/RPi-WD-Packet-Interface#1]
I can't find a match for most of the Device #'s in the BOM.  For example:
C1 is show as 0.1  I assume that some sort of 0.1 uf capacitor but what kind, what specs, what size.  An internet search on Device #'s and Package numbers only finds matches for  PCB layout programs.

How do I order parts that will work and that will fit on the circuit board?

Thanks,
Irv

**Comment by jaymzx** [comment]
Sorry for the confusion. 0.1 is indeed 0.1uf, and is a standard ceramic capacitor. The dimensions in the BOM are exported from Eagle, so they refer to the footprint size. For the 0.1uf ceramic caps, that is 2.5x5.0mm. You can use whatever you have available, however, I recommend something at least 16V. Most ceramics that size begin around 50V. All resistors are 1/8 or 1/4W, whatever you have handy.
