### ISSUE TITLE
Parts from BOM

### ISSUE THREAD

**Issue by cbr600** [jaymzx/RPi-WD-Packet-Interface#3]
I have downloaded the files, the BOM, purchased the PCB, imported them in Eagle, but there's no actual information on parts to use.  The numbers and values work from some parts but not all (eg. capacitors).  How many watts the resistors need to take? etc.

How do I get to purchasing the needed parts? Sorry for posting here but could not reach the author otherwise.

**Comment by hsand** [comment]
I had the same question, but found some clarifications on a previously closed issue: https://github.com/jaymzx/RPi-WD-Packet-Interface/issues/1

**Comment by cbr600** [comment]
Wow. Your search Fu is strong. I looked all over.  Or so  I thought...

Thanks!
